### ISSUE TITLE
dependency failure on compilation: node_sass

### ISSUE THREAD

**Issue by laurencefass** [tomastrajan/angular-ngrx-material-starter#467]
**## Minimal reproduction of the bug with instructions:**

bash-4.4# npm start

> angular-ngrx-material-starter@7.4.0 start /app/ng/ng-material
> ng serve --open

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 69% building modules 523/524 modules 1 active ...henticated/authenticated.component.scssBrowserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Date: 2019-06-11T09:42:27.863Z
Hash: 68903600c3507606799e
Time: 42831ms
chunk {app-examples-examples-module} app-examples-examples-module.js, app-examples-examples-module.js.map (app-examples-examples-module) 164 kB  [rendered]
chunk {main} main.js, main.js.map (main) 194 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 537 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.85 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 19.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.22 MB [initial] [rendered]

ERROR in ./src/styles-app-loading.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles-app-loading.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/app.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/settings/components/settings-container.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/static/about/about.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/static/features/features.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/form/components/form.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/crud/components/crud.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/notifications/components/notifications.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/stock-market/components/stock-market-container.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/todos/components/todos-container.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/examples/examples.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/theming/child/child.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/examples/theming/parent/parent.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/shared/big-input/big-input-action.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/app/shared/big-input/big-input.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (/app/ng/ng-material/node_modules/sass-loader/lib/loader.js:46:72)
ℹ ｢wdm｣: Failed to compile.

## Expected behavior:

easy install. no unmet dependency issues.

## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[ ] No
[ x ] Unsure.

thanks

**Comment by klauvi** [comment]
This is most likely a node version issue. If you are using node version 11 or 12 you need to use version 10.x instead.

**Comment by tomastrajan** [comment]
@laurencefass & @klauvi  the project was updated to Angular 8, does this behavior still persist ?

**Comment by klauvi** [comment]
@tomastrajan @laurencefass Tried this just now using node v12.0.0. Works for me.

I did however get an error when running npm install:
npm ERR! 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz

Checked the package info and noticed they have versions 0.7.1 and 0.7.3 but version 0.7.2 doesn't have a tarball available. Tried yarn install and that worked fine.

This might be an issue on my computer though, got lots of other weird errors.
